deploy_definition_path: ./definitions
db.type: ~
db.host: ~
db.port: ~
db.user: root
db.password: ~
db.database: test
shopware.path: C:\xampp\xampp72\htdocs\shopware
shell.aliases:
  "mysql": C:\xampp\xampp72\mysql\bin\mysql.exe