migration_definition_path: ./migrations
mysql.host: localhost
mysql.port: 3306
mysql.username: root
mysql.password: ~
mysql.database: ~
mysql.bin: ~
oxid.path: /var/www/oxid
shopware.path: /var/www/shopware